language: python
sudo: false
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
env:
  - DJANGO=1.8.14
  - DJANGO=1.9.9
  - DJANGO=1.10.0
install:
    - pip install --quiet --upgrade -r requirements.txt
    - pip install --quiet --upgrade setuptools wheel
    - pip install --quiet --upgrade Django==$DJANGO
script:
    - python -m pip install -U pip
    - inv test
    - inv build
    - inv test_install
    - inv coverage
after_success:
    - coveralls
notifications:
    email: false
matrix:
  exclude:
    - python: 3.3
      env: DJANGO=1.4.0
    - python: 3.3
      env: DJANGO=1.4.20
    - python: 3.3
      env: DJANGO=1.10.0
    - python: 3.4
      env: DJANGO=1.4.0
    - python: 3.4
      env: DJANGO=1.4.20
    - python: pypy
      env: DJANGO=1.5
    - python: pypy
      env: DJANGO=1.5.12
